version: "3.8"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/nginx.docker
    container_name: z-nginx
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
    networks:
      app-network:
        ipv4_address: 172.28.1.19

  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.docker
    container_name: z-php
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
    networks:
      app-network:
        ipv4_address: 172.28.1.20

  memcached:
    build:
      context: ./
      dockerfile: ./docker/memcached/memcached.docker
    container_name: z-memcached
    restart: always
    tty: true
    ports:
      - 11211:11211
    networks:
      app-network:
        ipv4_address: 172.28.1.17
